# Makefile.in generated by automake 1.11.1 from Makefile.am.
# src/Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002,
# 2003, 2004, 2005, 2006, 2007, 2008, 2009  Free Software Foundation,
# Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.



# -*- Makefile -*-
# $Id: global-rules 5784 2009-12-14 19:51:06Z christi $

#
# this file should be included into any Makefile.am so that we can
# easily introduce new global rules. DO NOT OVERUSE!
#

# -*- Makefile -*-
# $Id: sourcescheck 6115 2010-09-01 19:17:42Z christi $

# -*- Makefile -*-
# $Id: sourcescheck 5183 2008-04-27 17:37:08Z christi $

# -*- Makefile -*-
# $Id: checklog 5890 2010-02-10 18:24:13Z christi $

#
# check-log
#
# This file implements the build-rules needed by the automated tests.
# "make check-log" will build the whole package and run all tests. For
# each test a log file under $(topsrc_dir)/check-log is created which
# contains the name of the test and what kind of test it was (build,
# lib, run, ...). If a test fails this is logged, but all otehr tests
# are still run.
#
# make OPTIONS:
# LOG_TIMING - specific command to measure the time needed for each test
#              example: "make LOG_TIMING='time -p' check-log"
#
# IMPLEMENTATION: check-log depends on different targets for different
# kinds of tests. These can run idividually by calling check-log-XXX.
# Possible variants are (in order of dependence)
#   - libs    (build all libraries)
#   - build   (build all applications and tests)
#   - test    (run each test from $(TESTS))
#   - sources (run sourcescheck in each directory)
#   - headers (run headercheck for each header)
#   - dir     (create dir entries for database, no actual tests are run)
#

# -*- Makefile -*-
# $Id: global-rules 5267 2008-09-10 10:45:42Z christi $


pkgdatadir = $(datadir)/dune-ofdft
pkgincludedir = $(includedir)/dune-ofdft
pkglibdir = $(libdir)/dune-ofdft
pkglibexecdir = $(libexecdir)/dune-ofdft
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_triplet = x86_64-unknown-linux-gnu
host_triplet = x86_64-unknown-linux-gnu
noinst_PROGRAMS = dune_ofdft$(EXEEXT)
DIST_COMMON = $(srcdir)/Makefile.am $(srcdir)/Makefile.in \
	$(top_srcdir)/am/checklog $(top_srcdir)/am/documentation \
	$(top_srcdir)/am/global-rules $(top_srcdir)/am/headercheck \
	$(top_srcdir)/am/sourcescheck
subdir = src
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/dependencies.m4 \
	$(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
mkinstalldirs = $(install_sh) -d
CONFIG_HEADER = $(top_builddir)/config.h
CONFIG_CLEAN_FILES =
CONFIG_CLEAN_VPATH_FILES =
PROGRAMS = $(noinst_PROGRAMS)
am_dune_ofdft_OBJECTS = dune_ofdft-dune_ofdft.$(OBJEXT)
dune_ofdft_OBJECTS = $(am_dune_ofdft_OBJECTS)
am__DEPENDENCIES_1 =
dune_ofdft_DEPENDENCIES = $(am__DEPENDENCIES_1) $(am__DEPENDENCIES_1) \
	$(am__DEPENDENCIES_1) $(am__DEPENDENCIES_1) \
	$(am__DEPENDENCIES_1) $(am__DEPENDENCIES_1) \
	$(am__DEPENDENCIES_1) $(am__DEPENDENCIES_1) \
	$(am__DEPENDENCIES_1) $(am__DEPENDENCIES_1) \
	$(am__DEPENDENCIES_1)
AM_V_lt = $(am__v_lt_$(V))
am__v_lt_ = $(am__v_lt_$(AM_DEFAULT_VERBOSITY))
am__v_lt_0 = --silent
dune_ofdft_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CXXLD) $(AM_CXXFLAGS) \
	$(CXXFLAGS) $(dune_ofdft_LDFLAGS) $(LDFLAGS) -o $@
DEFAULT_INCLUDES = -I. -I$(top_builddir)
depcomp = $(SHELL) $(top_srcdir)/depcomp
am__depfiles_maybe = depfiles
am__mv = mv -f
CXXCOMPILE = $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
LTCXXCOMPILE = $(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) \
	$(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) \
	$(AM_CXXFLAGS) $(CXXFLAGS)
AM_V_CXX = $(am__v_CXX_$(V))
am__v_CXX_ = $(am__v_CXX_$(AM_DEFAULT_VERBOSITY))
am__v_CXX_0 = @echo "  CXX   " $@;
AM_V_at = $(am__v_at_$(V))
am__v_at_ = $(am__v_at_$(AM_DEFAULT_VERBOSITY))
am__v_at_0 = @
CXXLD = $(CXX)
CXXLINK = $(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CXXLD) $(AM_CXXFLAGS) \
	$(CXXFLAGS) $(AM_LDFLAGS) $(LDFLAGS) -o $@
AM_V_CXXLD = $(am__v_CXXLD_$(V))
am__v_CXXLD_ = $(am__v_CXXLD_$(AM_DEFAULT_VERBOSITY))
am__v_CXXLD_0 = @echo "  CXXLD " $@;
AM_V_GEN = $(am__v_GEN_$(V))
am__v_GEN_ = $(am__v_GEN_$(AM_DEFAULT_VERBOSITY))
am__v_GEN_0 = @echo "  GEN   " $@;
SOURCES = $(dune_ofdft_SOURCES)
DIST_SOURCES = $(dune_ofdft_SOURCES)
RECURSIVE_TARGETS = all-recursive check-recursive dvi-recursive \
	html-recursive info-recursive install-data-recursive \
	install-dvi-recursive install-exec-recursive \
	install-html-recursive install-info-recursive \
	install-pdf-recursive install-ps-recursive install-recursive \
	installcheck-recursive installdirs-recursive pdf-recursive \
	ps-recursive uninstall-recursive
RECURSIVE_CLEAN_TARGETS = mostlyclean-recursive clean-recursive	\
  distclean-recursive maintainer-clean-recursive
AM_RECURSIVE_TARGETS = $(RECURSIVE_TARGETS:-recursive=) \
	$(RECURSIVE_CLEAN_TARGETS:-recursive=) tags TAGS ctags CTAGS \
	distdir
ETAGS = etags
CTAGS = ctags
DIST_SUBDIRS = $(SUBDIRS)
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
am__relativize = \
  dir0=`pwd`; \
  sed_first='s,^\([^/]*\)/.*$$,\1,'; \
  sed_rest='s,^[^/]*/*,,'; \
  sed_last='s,^.*/\([^/]*\)$$,\1,'; \
  sed_butlast='s,/*[^/]*$$,,'; \
  while test -n "$$dir1"; do \
    first=`echo "$$dir1" | sed -e "$$sed_first"`; \
    if test "$$first" != "."; then \
      if test "$$first" = ".."; then \
        dir2=`echo "$$dir0" | sed -e "$$sed_last"`/"$$dir2"; \
        dir0=`echo "$$dir0" | sed -e "$$sed_butlast"`; \
      else \
        first2=`echo "$$dir2" | sed -e "$$sed_first"`; \
        if test "$$first2" = "$$first"; then \
          dir2=`echo "$$dir2" | sed -e "$$sed_rest"`; \
        else \
          dir2="../$$dir2"; \
        fi; \
        dir0="$$dir0"/"$$first"; \
      fi; \
    fi; \
    dir1=`echo "$$dir1" | sed -e "$$sed_rest"`; \
  done; \
  reldir="$$dir2"
ACLOCAL = ${SHELL} /home/sj/dune/dune-ofdft/missing --run aclocal-1.11
ACLOCAL_AMFLAGS = -I . -I m4 -I /home/sj/dune/dune-common/m4 -I /home/sj/dune/dune-grid/m4 -I /home/sj/dune/dune-istl/m4 -I /home/sj/dune/dune-localfunctions/m4 -I /home/sj/dune/dune-pdelab/m4
ALBERTA1D_CPPFLAGS = 
ALBERTA1D_LDFLAGS = 
ALBERTA1D_LIBS = 
ALBERTA2D_CPPFLAGS = 
ALBERTA2D_LDFLAGS = 
ALBERTA2D_LIBS = 
ALBERTA3D_CPPFLAGS = 
ALBERTA3D_LDFLAGS = 
ALBERTA3D_LIBS = 
ALBERTA4D_CPPFLAGS = 
ALBERTA4D_LDFLAGS = 
ALBERTA4D_LIBS = 
ALBERTA5D_CPPFLAGS = 
ALBERTA5D_LDFLAGS = 
ALBERTA5D_LIBS = 
ALBERTA6D_CPPFLAGS = 
ALBERTA6D_LDFLAGS = 
ALBERTA6D_LIBS = 
ALBERTA7D_CPPFLAGS = 
ALBERTA7D_LDFLAGS = 
ALBERTA7D_LIBS = 
ALBERTA8D_CPPFLAGS = 
ALBERTA8D_LDFLAGS = 
ALBERTA8D_LIBS = 
ALBERTA9D_CPPFLAGS = 
ALBERTA9D_LDFLAGS = 
ALBERTA9D_LIBS = 
ALBERTAROOT = 
ALBERTA_BASE_LIBS = 
ALBERTA_CPPFLAGS = 
ALBERTA_DIM = 
ALBERTA_DIM_CPPFLAGS = 
ALBERTA_INCLUDE_CPPFLAGS = 
ALBERTA_LDFLAGS = 
ALBERTA_LIBPATHFLAGS = 
ALBERTA_LIBS = 
ALGLIB_CPPFLAGS = 
ALGLIB_LIBS = 
ALL_PKG_CPPFLAGS =   -I/home/sj/dune/dune-common  -I/home/sj/dune/dune-grid  -I/home/sj/dune/dune-istl  -I/home/sj/dune/dune-localfunctions  -I/home/sj/dune/dune-pdelab   ${DUNEMPICPPFLAGS} -I/home/sj/dune/dune-common -DGRIDDIM=$(GRIDDIM) -DWORLDDIM=$(WORLDDIM) -D$(GRIDTYPE) ${UG_CPPFLAGS} -I/home/sj/dune/dune-grid ${SUPERLU_CPPFLAGS} -I/home/sj/dune/dune-istl -I/home/sj/dune/dune-localfunctions -I/home/sj/dune/dune-pdelab
ALL_PKG_LDFLAGS =              ${DUNEMPILDFLAGS}   ${UG_LDFLAGS}     
ALL_PKG_LIBS =    ${SUPERLU_LIBS} -L/home/sj/dune/dune-grid/lib -ldunegrid ${UG_LIBS}  -L/home/sj/dune/dune-common/lib -ldunecommon ${DUNEMPILIBS}     -L/home/sj/dune/dune-grid/lib -ldunegrid -L/home/sj/dune/dune-common/lib -ldunecommon  -L/home/sj/dune/dune-common/lib -ldunecommon   -L/home/sj/dune/dune-grid/lib -ldunegrid  -L/home/sj/dune/dune-common/lib -ldunecommon      -lm 
ALUGRID_CPPFLAGS = 
ALUGRID_LDFLAGS = 
ALUGRID_LIBS = 
AMIRAMESH_CPPFLAGS = 
AMIRAMESH_LDFLAGS = 
AMIRAMESH_LIBS = 
AMTAR = ${SHELL} /home/sj/dune/dune-ofdft/missing --run tar
AM_CPPFLAGS =  -I/home/sj/dune/dune-common -I/home/sj/dune/dune-grid -I/home/sj/dune/dune-istl -I/home/sj/dune/dune-localfunctions -I/home/sj/dune/dune-pdelab
AM_DEFAULT_VERBOSITY = 1
AM_LDFLAGS =           
AR = ar
AUTOCONF = ${SHELL} /home/sj/dune/dune-ofdft/missing --run autoconf
AUTOHEADER = ${SHELL} /home/sj/dune/dune-ofdft/missing --run autoheader
AUTOMAKE = ${SHELL} /home/sj/dune/dune-ofdft/missing --run automake-1.11
AWK = gawk
BIBTEX = bibtex
BLAS_LIBS = -lcblas -lf77blas -latlas
BOOST_CPPFLAGS = -I/include/boost-0  -DENABLE_BOOST
BOOST_LDFLAGS = -L/lib64
CC = gcc
CCDEPMODE = depmode=gcc3
CFLAGS = -g -O2 -Wall
CONVERT = convert
CPP = gcc -E
CPPFLAGS = 
CXX = g++ -std=c++0x
CXXCPP = g++ -E -std=c++0x
CXXDEPMODE = depmode=gcc3
CXXFLAGS = -g -O2
CYGPATH_W = echo
DEFS = -DHAVE_CONFIG_H
DEPDIR = .deps
DOT = dot
DOXYGEN = doxygen
DSYMUTIL = 
DUMPBIN = 
DUNEALBERTA_LIBPATHFLAGS = 
DUNEMPICPPFLAGS = 
DUNEMPILDFLAGS = 
DUNEMPILIBS = 
DUNEWEBDIR = no
DUNE_COMMON_CPPFLAGS = 
DUNE_COMMON_LDFLAGS = 
DUNE_COMMON_LIBDIR = /home/sj/dune/dune-common/lib
DUNE_COMMON_LIBS = 
DUNE_COMMON_ROOT = /home/sj/dune/dune-common
DUNE_COMMON_VERSION = 2.2-svn
DUNE_COMMON_VERSION_MAJOR = 2
DUNE_COMMON_VERSION_MINOR = 2
DUNE_COMMON_VERSION_REVISION = 0
DUNE_CPPFLAGS =  -I/home/sj/dune/dune-common -I/home/sj/dune/dune-grid -I/home/sj/dune/dune-istl -I/home/sj/dune/dune-localfunctions -I/home/sj/dune/dune-pdelab
DUNE_GRID_CPPFLAGS = 
DUNE_GRID_LDFLAGS = 
DUNE_GRID_LIBDIR = /home/sj/dune/dune-grid/lib
DUNE_GRID_LIBS = 
DUNE_GRID_ROOT = /home/sj/dune/dune-grid
DUNE_GRID_VERSION = 2.2-svn
DUNE_GRID_VERSION_MAJOR = 2
DUNE_GRID_VERSION_MINOR = 2
DUNE_GRID_VERSION_REVISION = 0
DUNE_ISTL_CPPFLAGS = 
DUNE_ISTL_LDFLAGS = 
DUNE_ISTL_LIBS = 
DUNE_ISTL_ROOT = /home/sj/dune/dune-istl
DUNE_ISTL_VERSION = 2.2-svn
DUNE_ISTL_VERSION_MAJOR = 2
DUNE_ISTL_VERSION_MINOR = 2
DUNE_ISTL_VERSION_REVISION = 0
DUNE_LDFLAGS =           
DUNE_LIBS =        -L/home/sj/dune/dune-grid/lib -ldunegrid  -L/home/sj/dune/dune-common/lib -ldunecommon 
DUNE_LOCALFUNCTIONS_CPPFLAGS = 
DUNE_LOCALFUNCTIONS_LDFLAGS = 
DUNE_LOCALFUNCTIONS_LIBS = 
DUNE_LOCALFUNCTIONS_ROOT = /home/sj/dune/dune-localfunctions
DUNE_LOCALFUNCTIONS_VERSION = 2.2-svn
DUNE_LOCALFUNCTIONS_VERSION_MAJOR = 2
DUNE_LOCALFUNCTIONS_VERSION_MINOR = 2
DUNE_LOCALFUNCTIONS_VERSION_REVISION = 0
DUNE_MAINTAINER_NAME = swayam.151@gmail.com
DUNE_MOD_NAME = dune-ofdft
DUNE_MOD_VERSION = 1
DUNE_OFDFT_VERSION = 1
DUNE_OFDFT_VERSION_MAJOR = 1
DUNE_OFDFT_VERSION_MINOR = 0
DUNE_OFDFT_VERSION_REVISION = 0
DUNE_PDELAB_CPPFLAGS = 
DUNE_PDELAB_LDFLAGS = 
DUNE_PDELAB_LIBS = 
DUNE_PDELAB_ROOT = /home/sj/dune/dune-pdelab
DUNE_PDELAB_VERSION = 0.1
DUNE_PDELAB_VERSION_MAJOR = 0
DUNE_PDELAB_VERSION_MINOR = 1
DUNE_PDELAB_VERSION_REVISION = 0
DVIPDF = dvipdf
DVIPS = dvips
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EGREP = /bin/grep -E
ENABLE_PARALLEL = 
EXEEXT = 
F77 = gfortran
FC = gfortran
FCFLAGS = -g -O2
FCLIBS =  -L/usr/lib/gcc/x86_64-linux-gnu/4.4.3 -L/usr/lib/gcc/x86_64-linux-gnu/4.4.3/../../../../lib -L/lib/../lib -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/4.4.3/../../.. -L/usr/lib/x86_64-linux-gnu -lgfortranbegin -lgfortran -lm
FFLAGS = -g -O2
FGREP = /bin/grep -F
FLIBS =  -L/usr/lib/gcc/x86_64-linux-gnu/4.4.3 -L/usr/lib/gcc/x86_64-linux-gnu/4.4.3/../../../../lib -L/lib/../lib -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/4.4.3/../../.. -L/usr/lib/x86_64-linux-gnu -lgfortranbegin -lgfortran -lm
GL_CFLAGS = -pthread
GL_CPPFLAGS = -pthread
GL_LDFLAGS = -pthread
GL_LIBS = -lGL  -lm
GMP_CPPFLAGS = 
GMP_LIBS = 
GRAPE_CPPFLAGS = 
GRAPE_LDFLAGS = 
GRAPE_LIBS = 
GREP = /bin/grep
GRIDDIM = 0
GRIDDIM_CPPFLAGS = -DGRIDDIM=$(GRIDDIM) -DWORLDDIM=$(WORLDDIM) -D$(GRIDTYPE)
GRIDTYPE = NOGRID
INKSCAPE = no
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
LAPACK_LIBS = 
LD = /usr/bin/ld -m elf_x86_64
LDFLAGS = 
LIBOBJS = 
LIBS =        -L/home/sj/dune/dune-grid/lib -ldunegrid  -L/home/sj/dune/dune-common/lib -ldunecommon 
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LIPO = 
LN_S = ln -s
LTLIBOBJS = 
MAKEINFO = ${SHELL} /home/sj/dune/dune-ofdft/missing --run makeinfo
METIS = 
METIS_INCLUDE = 
METIS_LDFLAGS = 
METIS_LIB = 
MKDIR_P = /bin/mkdir -p
MPICC = 
MPILIBS = 
MPI_CPPFLAGS =  -D DEPRECATED_MPI_CPPFLAGS_USED
MPI_LDFLAGS = 
MPI_VERSION = 
NM = /usr/bin/nm -B
NMEDIT = 
OBJDUMP = objdump
OBJEXT = o
OTOOL = 
OTOOL64 = 
PACKAGE = dune-ofdft
PACKAGE_BUGREPORT = swayam.151@gmail.com
PACKAGE_NAME = dune-ofdft
PACKAGE_STRING = dune-ofdft 1
PACKAGE_TARNAME = dune-ofdft
PACKAGE_URL = 
PACKAGE_VERSION = 1
PARDISO_LIBS = 
PARMETIS = 
PARMETIS_CPPFLAGS = 
PARMETIS_LDFLAGS = 
PARMETIS_LIBS = 
PATH_SEPARATOR = :
PERL = perl
PKG_CONFIG = /usr/bin/pkg-config
PSURFACE_CPPFLAGS = 
PSURFACE_LDFLAGS = 
PSURFACE_LIBS = 
PTHREAD_CC = gcc
PTHREAD_CFLAGS = -pthread
PTHREAD_LIBS = 
RANLIB = ranlib
REQUIRES =  dune-common   dune-grid   dune-istl   dune-grid-howto   dune-localfunctions   dune-pdelab  
SED = /bin/sed
SET_MAKE = 
SHELL = /bin/bash
STRIP = strip
SUPERLU_CPPFLAGS = 
SUPERLU_DIST_CPPFLAGS = -I/usr/local/SRC 
SUPERLU_DIST_LDFLAGS = -L/usr/local/ 
SUPERLU_DIST_LIBS = 
SUPERLU_LIBS = 
TEX = latex
UG_CPPFLAGS = -I/home/sj/dune/UG/ug/include/ug   -DENABLE_UG
UG_LDFLAGS = 
UG_LIBS = -L/home/sj/dune/UG/ug/lib   -lugS2 -lugS3 -ldevS
VERSION = 1
WML = true
WORLDDIM = $(GRIDDIM)
XMKMF = 
X_CFLAGS = 
X_EXTRA_LIBS = 
X_LIBS = 
X_PRE_LIBS = 
abs_builddir = /home/sj/dune/dune-ofdft/src
abs_srcdir = /home/sj/dune/dune-ofdft/src
abs_top_builddir = /home/sj/dune/dune-ofdft
abs_top_srcdir = /home/sj/dune/dune-ofdft
ac_ct_CC = gcc
ac_ct_CXX = g++
ac_ct_DUMPBIN = 
ac_ct_F77 = gfortran
ac_ct_FC = gfortran
acx_pthread_config = 
am__include = include
am__leading_dot = .
am__quote = 
am__tar = tar --format=posix -chf - "$$tardir"
am__untar = tar -xf -
am_dir = /home/sj/dune/dune-common/am
bindir = ${exec_prefix}/bin
build = x86_64-unknown-linux-gnu
build_alias = 
build_cpu = x86_64
build_os = linux-gnu
build_vendor = unknown
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
host = x86_64-unknown-linux-gnu
host_alias = 
host_cpu = x86_64
host_os = linux-gnu
host_vendor = unknown
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /home/sj/dune/dune-ofdft/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
lt_ECHO = echo
mandir = ${datarootdir}/man
mkdir_p = /bin/mkdir -p
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /usr/local
program_transform_name = s,x,x,
psdir = ${docdir}
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target_alias = 
top_build_prefix = ../
top_builddir = ..
top_srcdir = ..
SUBDIRS = 
dune_ofdft_SOURCES = dune_ofdft.cc
dune_ofdft_CPPFLAGS = $(AM_CPPFLAGS) \
	$(DUNEMPICPPFLAGS) \
	$(UG_CPPFLAGS) \
	$(AMIRAMESH_CPPFLAGS) \
	$(ALBERTA_CPPFLAGS) \
	$(ALUGRID_CPPFLAGS)

# The libraries have to be given in reverse order (most basic libraries
# last).  Also, due to some misunderstanding, a lot of libraries include the
# -L option in LDFLAGS instead of LIBS -- so we have to include the LDFLAGS
# here as well.
dune_ofdft_LDADD = \
	$(DUNE_LDFLAGS) $(DUNE_LIBS) \
	$(ALUGRID_LDFLAGS) $(ALUGRID_LIBS) \
	$(ALBERTA_LDFLAGS) $(ALBERTA_LIBS) \
	$(AMIRAMESH_LDFLAGS) $(AMIRAMESH_LIBS) \
	$(UG_LDFLAGS) $(UG_LIBS) \
	$(DUNEMPILIBS)	\
	$(LDADD)

dune_ofdft_LDFLAGS = $(AM_LDFLAGS) \
	$(DUNEMPILDFLAGS) \
	$(UG_LDFLAGS) \
	$(AMIRAMESH_LDFLAGS) \
	$(ALBERTA_LDFLAGS) \
	$(ALUGRID_LDFLAGS) \
	$(DUNE_LDFLAGS)


# don't follow the full GNU-standard
# we need automake 1.5
AUTOMAKE_OPTIONS = foreign 1.5

# pass most important options when "make distcheck" is used
DISTCHECK_CONFIGURE_FLAGS = --with-dune-common=$(DUNE_COMMON_ROOT) --with-dune-grid=$(DUNE_GRID_ROOT) --with-dune-istl=$(DUNE_ISTL_ROOT) --with-dune-grid-howto=$(DUNE_GRID_HOWTO_ROOT) --with-dune-localfunctions=$(DUNE_LOCALFUNCTIONS_ROOT) --with-dune-pdelab=$(DUNE_PDELAB_ROOT)  CXX="$(CXX)" CC="$(CC)"
sourcescheck_IGNORE = aclocal.m4 dependencies.m4
sourcescheck_LIST = $(SOURCES) $(DIST_SOURCES) $(HEADERS) $(DIST_HEADERS) \
	$(sourcescheck_NOSOURCES) $(dist_noinst_DATA) $(EXTRA_DIST)

headercheck_PATTERN = *.hh
LOG_FILE = $(top_srcdir)/check-log.log
LOG_DIR = $(top_srcdir)/check-log
LOG_STORE = $(SHELL) $(DUNE_COMMON_ROOT)/bin/check-log-store $(LOG_FILE) $(LOG_DIR)
LOG_TIMING = 
LOG_SET_OPTIONS = \
	path=`test "$(subdir)" = "." && \
	echo "/dune-ofdft" || echo "/dune-ofdft/$(subdir)"`; \
	ppath=`dirname $$path`; \
	dir=`basename $$path`

all: all-recursive

.SUFFIXES:
.SUFFIXES: .cc .lo .o .obj
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am $(top_srcdir)/am/global-rules $(top_srcdir)/am/sourcescheck $(top_srcdir)/am/headercheck $(top_srcdir)/am/checklog $(top_srcdir)/am/documentation $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      ( cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh ) \
	        && { if test -f $@; then exit 0; else break; fi; }; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --foreign src/Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --foreign src/Makefile
.PRECIOUS: Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $(subdir)/$@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $(subdir)/$@ $(am__depfiles_maybe);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh

$(top_srcdir)/configure:  $(am__configure_deps)
	cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh
$(am__aclocal_m4_deps):

clean-noinstPROGRAMS:
	@list='$(noinst_PROGRAMS)'; test -n "$$list" || exit 0; \
	echo " rm -f" $$list; \
	rm -f $$list || exit $$?; \
	test -n "$(EXEEXT)" || exit 0; \
	list=`for p in $$list; do echo "$$p"; done | sed 's/$(EXEEXT)$$//'`; \
	echo " rm -f" $$list; \
	rm -f $$list
dune_ofdft$(EXEEXT): $(dune_ofdft_OBJECTS) $(dune_ofdft_DEPENDENCIES) 
	@rm -f dune_ofdft$(EXEEXT)
	$(AM_V_CXXLD)$(dune_ofdft_LINK) $(dune_ofdft_OBJECTS) $(dune_ofdft_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

include ./$(DEPDIR)/dune_ofdft-dune_ofdft.Po

.cc.o:
	$(AM_V_CXX)$(CXXCOMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ $<
	$(AM_V_at)$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	$(AM_V_CXX) \
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXXCOMPILE) -c -o $@ $<

.cc.obj:
	$(AM_V_CXX)$(CXXCOMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ `$(CYGPATH_W) '$<'`
	$(AM_V_at)$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	$(AM_V_CXX) \
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXXCOMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

.cc.lo:
	$(AM_V_CXX)$(LTCXXCOMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ $<
	$(AM_V_at)$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Plo
#	$(AM_V_CXX) \
#	source='$<' object='$@' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LTCXXCOMPILE) -c -o $@ $<

dune_ofdft-dune_ofdft.o: dune_ofdft.cc
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(dune_ofdft_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT dune_ofdft-dune_ofdft.o -MD -MP -MF $(DEPDIR)/dune_ofdft-dune_ofdft.Tpo -c -o dune_ofdft-dune_ofdft.o `test -f 'dune_ofdft.cc' || echo '$(srcdir)/'`dune_ofdft.cc
	$(AM_V_at)$(am__mv) $(DEPDIR)/dune_ofdft-dune_ofdft.Tpo $(DEPDIR)/dune_ofdft-dune_ofdft.Po
#	$(AM_V_CXX) \
#	source='dune_ofdft.cc' object='dune_ofdft-dune_ofdft.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(dune_ofdft_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o dune_ofdft-dune_ofdft.o `test -f 'dune_ofdft.cc' || echo '$(srcdir)/'`dune_ofdft.cc

dune_ofdft-dune_ofdft.obj: dune_ofdft.cc
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(dune_ofdft_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT dune_ofdft-dune_ofdft.obj -MD -MP -MF $(DEPDIR)/dune_ofdft-dune_ofdft.Tpo -c -o dune_ofdft-dune_ofdft.obj `if test -f 'dune_ofdft.cc'; then $(CYGPATH_W) 'dune_ofdft.cc'; else $(CYGPATH_W) '$(srcdir)/dune_ofdft.cc'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/dune_ofdft-dune_ofdft.Tpo $(DEPDIR)/dune_ofdft-dune_ofdft.Po
#	$(AM_V_CXX) \
#	source='dune_ofdft.cc' object='dune_ofdft-dune_ofdft.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(dune_ofdft_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o dune_ofdft-dune_ofdft.obj `if test -f 'dune_ofdft.cc'; then $(CYGPATH_W) 'dune_ofdft.cc'; else $(CYGPATH_W) '$(srcdir)/dune_ofdft.cc'; fi`

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs

# This directory's subdirectories are mostly independent; you can cd
# into them and run `make' without going through this Makefile.
# To change the values of `make' variables: instead of editing Makefiles,
# (1) if the variable is set in `config.status', edit `config.status'
#     (which will cause the Makefiles to be regenerated when you run `make');
# (2) otherwise, pass the desired values on the `make' command line.
$(RECURSIVE_TARGETS):
	@fail= failcom='exit 1'; \
	for f in x $$MAKEFLAGS; do \
	  case $$f in \
	    *=* | --[!k]*);; \
	    *k*) failcom='fail=yes';; \
	  esac; \
	done; \
	dot_seen=no; \
	target=`echo $@ | sed s/-recursive//`; \
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  echo "Making $$target in $$subdir"; \
	  if test "$$subdir" = "."; then \
	    dot_seen=yes; \
	    local_target="$$target-am"; \
	  else \
	    local_target="$$target"; \
	  fi; \
	  ($(am__cd) $$subdir && $(MAKE) $(AM_MAKEFLAGS) $$local_target) \
	  || eval $$failcom; \
	done; \
	if test "$$dot_seen" = "no"; then \
	  $(MAKE) $(AM_MAKEFLAGS) "$$target-am" || exit 1; \
	fi; test -z "$$fail"

$(RECURSIVE_CLEAN_TARGETS):
	@fail= failcom='exit 1'; \
	for f in x $$MAKEFLAGS; do \
	  case $$f in \
	    *=* | --[!k]*);; \
	    *k*) failcom='fail=yes';; \
	  esac; \
	done; \
	dot_seen=no; \
	case "$@" in \
	  distclean-* | maintainer-clean-*) list='$(DIST_SUBDIRS)' ;; \
	  *) list='$(SUBDIRS)' ;; \
	esac; \
	rev=''; for subdir in $$list; do \
	  if test "$$subdir" = "."; then :; else \
	    rev="$$subdir $$rev"; \
	  fi; \
	done; \
	rev="$$rev ."; \
	target=`echo $@ | sed s/-recursive//`; \
	for subdir in $$rev; do \
	  echo "Making $$target in $$subdir"; \
	  if test "$$subdir" = "."; then \
	    local_target="$$target-am"; \
	  else \
	    local_target="$$target"; \
	  fi; \
	  ($(am__cd) $$subdir && $(MAKE) $(AM_MAKEFLAGS) $$local_target) \
	  || eval $$failcom; \
	done && test -z "$$fail"
tags-recursive:
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  test "$$subdir" = . || ($(am__cd) $$subdir && $(MAKE) $(AM_MAKEFLAGS) tags); \
	done
ctags-recursive:
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  test "$$subdir" = . || ($(am__cd) $$subdir && $(MAKE) $(AM_MAKEFLAGS) ctags); \
	done

ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
	list='$(SOURCES) $(HEADERS) $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	mkid -fID $$unique
tags: TAGS

TAGS: tags-recursive $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	set x; \
	here=`pwd`; \
	if ($(ETAGS) --etags-include --version) >/dev/null 2>&1; then \
	  include_option=--etags-include; \
	  empty_fix=.; \
	else \
	  include_option=--include; \
	  empty_fix=; \
	fi; \
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  if test "$$subdir" = .; then :; else \
	    test ! -f $$subdir/TAGS || \
	      set "$$@" "$$include_option=$$here/$$subdir/TAGS"; \
	  fi; \
	done; \
	list='$(SOURCES) $(HEADERS)  $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: CTAGS
CTAGS: ctags-recursive $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	list='$(SOURCES) $(HEADERS)  $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags

distdir: $(DISTFILES)
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
	@list='$(DIST_SUBDIRS)'; for subdir in $$list; do \
	  if test "$$subdir" = .; then :; else \
	    test -d "$(distdir)/$$subdir" \
	    || $(MKDIR_P) "$(distdir)/$$subdir" \
	    || exit 1; \
	  fi; \
	done
	@list='$(DIST_SUBDIRS)'; for subdir in $$list; do \
	  if test "$$subdir" = .; then :; else \
	    dir1=$$subdir; dir2="$(distdir)/$$subdir"; \
	    $(am__relativize); \
	    new_distdir=$$reldir; \
	    dir1=$$subdir; dir2="$(top_distdir)"; \
	    $(am__relativize); \
	    new_top_distdir=$$reldir; \
	    echo " (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) top_distdir="$$new_top_distdir" distdir="$$new_distdir" \\"; \
	    echo "     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)"; \
	    ($(am__cd) $$subdir && \
	      $(MAKE) $(AM_MAKEFLAGS) \
	        top_distdir="$$new_top_distdir" \
	        distdir="$$new_distdir" \
		am__remove_distdir=: \
		am__skip_length_check=: \
		am__skip_mode_fix=: \
	        distdir) \
	      || exit 1; \
	  fi; \
	done
check-am: all-am
check: check-recursive
all-am: Makefile $(PROGRAMS)
installdirs: installdirs-recursive
installdirs-am:
install: install-recursive
install-exec: install-exec-recursive
install-data: install-data-recursive
uninstall: uninstall-recursive

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-recursive
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	  install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	  `test -z '$(STRIP)' || \
	    echo "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'"` install
mostlyclean-generic:

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-recursive

clean-am: clean-generic clean-libtool clean-noinstPROGRAMS \
	mostlyclean-am

distclean: distclean-recursive
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-tags

dvi: dvi-recursive

dvi-am:

html: html-recursive

html-am:

info: info-recursive

info-am:

install-data-am: install-data-local

install-dvi: install-dvi-recursive

install-dvi-am:

install-exec-am:

install-html: install-html-recursive

install-html-am:

install-info: install-info-recursive

install-info-am:

install-man:

install-pdf: install-pdf-recursive

install-pdf-am:

install-ps: install-ps-recursive

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-recursive
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic \
	maintainer-clean-local

mostlyclean: mostlyclean-recursive

mostlyclean-am: mostlyclean-compile mostlyclean-generic \
	mostlyclean-libtool

pdf: pdf-recursive

pdf-am:

ps: ps-recursive

ps-am:

uninstall-am: uninstall-local

.MAKE: $(RECURSIVE_CLEAN_TARGETS) $(RECURSIVE_TARGETS) ctags-recursive \
	install-am install-strip tags-recursive

.PHONY: $(RECURSIVE_CLEAN_TARGETS) $(RECURSIVE_TARGETS) CTAGS GTAGS \
	all all-am check check-am clean clean-generic clean-libtool \
	clean-noinstPROGRAMS ctags ctags-recursive distclean \
	distclean-compile distclean-generic distclean-libtool \
	distclean-tags distdir dvi dvi-am html html-am info info-am \
	install install-am install-data install-data-am \
	install-data-local install-dvi install-dvi-am install-exec \
	install-exec-am install-html install-html-am install-info \
	install-info-am install-man install-pdf install-pdf-am \
	install-ps install-ps-am install-strip installcheck \
	installcheck-am installdirs installdirs-am maintainer-clean \
	maintainer-clean-generic maintainer-clean-local mostlyclean \
	mostlyclean-compile mostlyclean-generic mostlyclean-libtool \
	pdf pdf-am ps ps-am tags tags-recursive uninstall uninstall-am \
	uninstall-local


sourcescheck: sourcescheck-recursive

#	@(for f in $(sourcescheck_LIST) fnord; do echo $$f; done) | \
#	 grep '\.[hc][hc]$$' | sort | uniq > header_CHECK.install
sourcescheck-am:
	@echo $(sourcescheck_LIST) | tr ' ' '\n' | \
	 grep '\.[hcm][hc4]$$' | sort | uniq > header_CHECK.install
	@(ls $(srcdir); echo $(sourcescheck_DUMMY)) | \
	 grep '\.[hcm][hc4]$$' | sort | uniq > header_CHECK.present
	@RESULT=0; \
	if diff header_CHECK.* | grep ^[\<\>] -q; then \
		echo "==== WARNING ===="; \
	    echo "Directory: $(srcdir)"; \
		echo "Files present but not installed:"; \
		diff -u header_CHECK.install header_CHECK.present | \
		grep -v ^+++ | grep ^+; \
		echo "Files listed for install but not present:"; \
		diff -u header_CHECK.install header_CHECK.present | \
		grep -v ^--- | grep ^-; \
		echo "==== END ===="; \
		RESULT=1; \
	fi; \
	rm -f header_CHECK.install header_CHECK.present; \
	exit $$RESULT

sourcescheck-recursive:
	@set fnord $$MAKEFLAGS; amf=$$2; \
	dot_seen=no; \
	target=`echo $@ | sed s/-recursive//`; \
	list='$(DIST_SUBDIRS)'; for subdir in $$list; do \
	  echo "Making $$target in $$subdir"; \
	  if test "$$subdir" = "."; then \
	    dot_seen=yes; \
	    local_target="$$target-am"; \
	  else \
	    local_target="$$target"; \
	  fi; \
	  (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) $$local_target) \
	   || case "$$amf" in *=*) exit 1;; *k*) fail=yes;; *) exit 1;; esac; \
	done; \
	if test "$$dot_seen" = "no"; then \
	  $(MAKE) $(AM_MAKEFLAGS) "$$target-am" || exit 1; \
	fi; test -z "$$fail"

.PHONY: sourcescheck sourcescheck-recursive sourcescheck-am

# set 
# headercheck_IGNORE = foo.hh
# to ignore foo.hh

hctest.o: hctest.cc
	$(CXX) -I$(top_builddir) -I$(top_srcdir) -DHEADERCHECK \
	  $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) \
	  $(DUNEMPICPPFLAGS) $(ALL_PKG_CPPFLAGS) -c -o $@ $<

headercheck:
	@if test "x$V" = "x"; then \
      SILENTSTR='V=$(AM_DEFAULT_VERBOSITY)' ; \
    fi; \
    if test "x$SILENT" = "x1"; then \
      SILENTSTR='V=0' ; \
    fi; \
    if test "x$SILENT" = "x0"; then \
      SILENTSTR='V=1' ; \
    fi; \
    if test x"$$HEADER" = "x"; then \
	  $(MAKE) $$SILENTSTR $(AM_MAKEFLAGS) headercheck-recursive; \
	else \
	  $(MAKE) $$SILENTSTR $(AM_MAKEFLAGS) headercheck-am; \
	fi

headercheck-am:
	@if test x"$$HEADER" != "x"; then \
	  list="$$HEADER"; \
	else \
	  pushd "$(srcdir)" > /dev/null; \
	  list=`echo $(headercheck_PATTERN)`; \
	  popd > /dev/null; \
	fi; \
    test -z "$$NO_CONFIG_H" && NO_CONFIG_H=0; \
	test "$$list" != "$(headercheck_PATTERN)" || exit 0; \
	for f in $$list; do \
	echo "$(headercheck_IGNORE)" | tr ' ' '\n' | grep -q "$$f"; \
	  if echo "$(headercheck_IGNORE)" | tr ' ' '\n' | grep -q "$$f"; then continue; fi; \
	  HEADER="$(subdir)/$$f"; \
	  echo "checking $$HEADER"; \
	  CCFILE=hctest.cc; \
	  OFILE=hctest.o; \
	  LOGFILE=hctest.log; \
	  rm -f $$CCFILE; \
	  test $$NO_CONFIG_H -ne 0 && echo "    without config.h" \
	    || echo "#include <config.h>" > $$CCFILE; \
	  echo "#include <$${HEADER}>" >> $$CCFILE; \
	  echo "#include <$${HEADER}>" >> $$CCFILE; \
	  echo "int main () { return 0; }" >> $$CCFILE; \
	  make 	$$OFILE > $$LOGFILE 2>&1; \
	  SUCCESS=$$?; \
	  if ! (test $$SUCCESS -eq 0 && test -e $$OFILE); then \
	    echo "Error in $$HEADER"; \
            test $V -ne 1 && echo "run with V=1 to show details" || cat $$LOGFILE; \
	  fi; \
	  rm -f $$OFILE; \
	  rm -f $$CCFILE; \
	  rm -f $$LOGFILE; \
	  test $$SUCCESS -eq 0 || exit $$SUCCESS; \
	done

headercheck-recursive:
	@set fnord $$MAKEFLAGS; amf=$$2; \
	dot_seen=no; \
	target=`echo $@ | sed s/-recursive//`; \
	list='$(DIST_SUBDIRS)'; for subdir in $$list; do \
	  echo "Making $$target in $(subdir)/$$subdir"; \
	  if test "$$subdir" = "."; then \
	    dot_seen=yes; \
	    local_target="$$target-am"; \
	  else \
	    local_target="$$target"; \
	  fi; \
	  (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) $$local_target) \
	   || case "$$amf" in *=*) exit 1;; *k*) fail=yes;; *) exit 1;; esac; \
	done; \
	if test "$$dot_seen" = "no"; then \
	  $(MAKE) $(AM_MAKEFLAGS) "$$target-am" || exit 1; \
	fi; test -z "$$fail"

.PHONY: headercheck headercheck-recursive headercheck-am

# vim:set filetype=automake:

$(DUNE_COMMON_ROOT)/bin/check-log-store: $(DUNE_COMMON_ROOT)/bin/check-log-store.in
	cd $(DUNE_COMMON_ROOT)/bin/ && $(MAKE) check-log-store

check-log: $(DUNE_COMMON_ROOT)/bin/check-log-store
check-log:
	rm -f $(LOG_FILE)

check-log: check-log-libs
check-log: check-log-build
check-log: check-log-test
check-log: check-log-sources
check-log: check-log-headers
check-log: check-log-dir

check-log-libs: check-log-libs-recursive
check-log-build: check-log-build-recursive
check-log-test: check-log-test-recursive
check-log-sources: check-log-sources-recursive
check-log-headers: check-log-headers-recursive
check-log-dir: check-log-dir-recursive

check-log-headers-am:
	$(LOG_SET_OPTIONS); \
	list=`echo $(headercheck_PATTERN)`; \
	test "$$list" != "$(headercheck_PATTERN)" || exit 0; \
	for f in $$list; do \
	  echo "$(headercheck_IGNORE)" | tr ' ' '\n' | grep -q "$$f"; \
	    if echo "$(headercheck_IGNORE)" | tr ' ' '\n' | grep -q "$$f"; then continue; fi; \
	  $(LOG_TIMING) ($(MAKE) headercheck-am SILENT=0 HEADER=$$f; \
	    $(MAKE) headercheck-am SILENT=0 HEADER=$$f NO_CONFIG_H=1) > $(LOG_FILE) 2>&1; \
	  $(LOG_STORE) "headercheck" "$$f" "$$path"; \
	done

check-log-sources-am:
	$(LOG_SET_OPTIONS); \
	$(LOG_TIMING) $(MAKE) sourcescheck-am > $(LOG_FILE) 2>&1; \
	$(LOG_STORE) "sources" "Makefile.am" "$$path"

check-log-libs-am:
	$(LOG_SET_OPTIONS); \
	for lib in $(LTLIBRARIES); do \
	  $(LOG_TIMING) ($(MAKE) $$lib) > $(LOG_FILE) 2>&1; \
	  $(LOG_STORE) "lib" "$$lib" "$$path"; \
	done;

check-log-build-am:
	$(LOG_SET_OPTIONS); \
	for target in $(check_PROGRAMS) $(PROGRAMS); do \
	  $(LOG_TIMING) ($(MAKE) $$target) > $(LOG_FILE) 2>&1; \
	  $(LOG_STORE) "build" "$$target" "$$path"; \
	done;

check-log-test-am:
	@LOG () { \
	  echo "$$1" > $(LOG_FILE).2; \
	  cat $(LOG_FILE) >> $(LOG_FILE).2; \
	  mv $(LOG_FILE).2 $(LOG_FILE); \
	}; \
	$(LOG_SET_OPTIONS); \
	for tst in $(TESTS); do \
	  if test -f ./$$tst; then dir=./; \
	  elif test -f $$tst; then dir=; \
	  else dir="$(srcdir)/"; fi; \
	  echo "TEST $${dir}$$tst"; \
	  if $(LOG_TIMING) $(TESTS_ENVIRONMENT) $${dir}$$tst > $(LOG_FILE) 2>&1; then \
	    case " $(XFAIL_TESTS) " in \
	    *" $$tst "*) \
	      LOG "ERROR: XPASS ($$tst)"; \
		  $(LOG_STORE) "run" "$$tst" "$$path" 1 0; \
	    ;; \
	    *) \
	      LOG "SUCCESS: PASS ($$tst)"; \
		  $(LOG_STORE) "run" "$$tst" "$$path" 0 0; \
	    ;; \
	    esac; \
	  elif test $$? -ne 77; then \
	    case " $(XFAIL_TESTS) " in \
	    *" $$tst "*) \
	      LOG "SUCCESS: XFAIL ($$tst)"; \
		  $(LOG_STORE) "run" "$$tst" "$$path" 0 0; \
	    ;; \
	    *) \
	      LOG "ERROR: FAIL ($$tst)"; \
		  $(LOG_STORE) "run" "$$tst" "$$path" 1 0; \
	    ;; \
	    esac; \
	  else \
	    LOG "WARNING: SKIP ($$tst)"; \
		$(LOG_STORE) "run" "$$tst" "$$path" 0 1; \
	  fi; \
	done;

check-log-dir-am:
	$(LOG_SET_OPTIONS); \
	$(LOG_STORE) "dir" "$$dir" "$$ppath"

check-log-libs-recursive \
check-log-build-recursive \
check-log-test-recursive \
check-log-sources-recursive \
check-log-headers-recursive \
check-log-dir-recursive:
	@set fnord $$MAKEFLAGS; amf=$$2; \
	dot_seen=no; \
	target=`echo $@ | sed s/-recursive//`; \
	list='$(DIST_SUBDIRS)'; for subdir in $$list; do \
	  echo "Making $$target in $$subdir"; \
	  if test "$$subdir" = "."; then \
	    dot_seen=yes; \
	    local_target="$$target-am"; \
	  else \
	    local_target="$$target"; \
	  fi; \
	  (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) $$local_target) \
	   || case "$$amf" in *=*) exit 1;; *k*) fail=yes;; *) exit 1;; esac; \
	done; \
	if test "$$dot_seen" = "no"; then \
	  $(MAKE) $(AM_MAKEFLAGS) "$$target-am" || exit 1; \
	fi; test -z "$$fail"

.PHONY: check-log \
	check-log-lib check-log-lib-am check-log-lib-recursive \
	check-log-build check-log-build-am check-log-build-recursive \
	check-log-test check-log-test-am check-log-test-recursive \
	check-log-sources check-log-sources-am check-log-sources-recursive \
	check-log-dir check-log-dir-am check-log-dir-recursive

maintainer-clean-local: doc-clean-am

###
# build doc / web-install recursively
doc-clean-am: clean-am doc-clean-documentation doc-clean-local
doc-am: doc-all-documentation doc-local
web-install-am: web-install-local

doc-local:
doc-clean-local:
web-install-local:

web-install: web-install-recursive
doc: doc-recursive
doc-clean: doc-clean-recursive

web-install-recursive \
doc-clean-recursive \
doc-recursive:
	@set fnord $$MAKEFLAGS; amf=$$2; \
	dot_seen=no; \
	target=`echo $@ | sed s/-recursive//`; \
	list='$(DIST_SUBDIRS)'; for subdir in $$list; do \
	  echo "Making $$target in $(subdir)/$$subdir"; \
	  if test "$$subdir" = "."; then \
	    dot_seen=yes; \
	    local_target="$$target-am"; \
	  else \
	    local_target="$$target"; \
	  fi; \
	  (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) $$local_target) \
	   || case "$$amf" in *=*) exit 1;; *k*) fail=yes;; *) exit 1;; esac; \
	done; \
	if test "$$dot_seen" = "no"; then \
	  $(MAKE) $(AM_MAKEFLAGS) "$$target-am" || exit 1; \
	fi; test -z "$$fail"

install-data-local: install-documentation
uninstall-local: uninstall-documentation

####
# "implementations"

doc-all-documentation: $(DOCFILES)

doc-clean-documentation:
	-test -z "$(DOCFILES)" || rm -f $(DOCFILES)

install-documentation: $(DOCFILES) install-documentation-local
	@$(NORMAL_INSTALL)
	test -z "$(docdir)" || $(mkdir_p) "$(DESTDIR)$(docdir)"
	@list='$(DOCFILES) $(DOCFILES_EXTRA)'; test -n "$(docdir)" || list=; \
	for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  echo "$$d$$p"; \
	done | \
	while read files; do \
	  echo " $(INSTALL_DATA) $$files '$(DESTDIR)$(docdir)'"; \
	  $(INSTALL_DATA) $$files "$(DESTDIR)$(docdir)" || exit $$?; \
	done

uninstall-documentation: uninstall-documentation-local
	@$(NORMAL_UNINSTALL)
	@list='$(DOCFILES) $(DOCFILES_EXTRA)'; test -n "$(docdir)" || list=; \
	files=`for p in $$list; do echo $$p; done | sed -e 's|^.*/||'`; \
	test -n "$$files" || exit 0; \
	echo " ( cd '$(DESTDIR)$(docdir)' && rm -f" $$files ")"; \
	cd "$(DESTDIR)$(docdir)" && rm -f $$files

.PHONY: uninstall-documentation uninstall-documentation-local \
	install-documentation install-documentation-local \
    doc-clean-am doc-am web-install-am \
    doc-local doc-clean-local web-install-local \
	web-install doc doc-clean \
	web-install-recursive doc-clean-recursive doc-recursive

# add "sourcescheck"-target testing if all source files are mentioned

# check consistency of the headers (see FS#394)

# add "check-log"-target to create automated build logs

# add "doc"-target to create and clean documentation

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
